[package]
name = "struct_scalpel"
version = "0.1.0"
edition = "2021"

[features]
default = ["dissect_std"]
dissect_std = []

[dependencies]
enable-ansi-support = "0.2.1"
struct_scalpel_proc_macro = { version="0.1.0", path="struct_scalpel_proc_macro" }
